// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'dialog-add-custom-tag'
  | 'dialog-apply-button'
  | 'dialog-calling-api'
  | 'dialog-cancel-button'
  | 'dialog-description'
  | 'dialog-error'
  | 'dialog-fetching-existing-tags'
  | 'dialog-generating-tags'
  | 'dialog-manual-input'
  | 'dialog-multiple-items-warning'
  | 'dialog-no-items-selected'
  | 'dialog-no-suggestions'
  | 'dialog-no-tags-selected'
  | 'dialog-tag-placeholder'
  | 'dialog-tags-applied'
  | 'dialog-title'
  | 'dialog-window-title'
  | 'menuitem-suggest-tags'
  | 'pref-api-key'
  | 'pref-api-model'
  | 'pref-api-provider'
  | 'pref-api-settings'
  | 'pref-custom-prompt'
  | 'pref-help'
  | 'pref-max-tags'
  | 'pref-prompt-help'
  | 'pref-prompt-settings'
  | 'pref-title'
  | 'prefs-title';
