// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "enableAISuggestions": boolean;
      "hotkeyEnabled": boolean;
      "hotkey": string;
      "apiProvider": string;
      "apiModel": string;
      "customPrompt": string;
      "maxTags": number;
    };
  }
}
